### ISSUE TITLE
JS error in browser console

### ISSUE THREAD

**Issue by pepperstreet** [sergeytolkachyov/WT-Content-Like#2]
Hello again, as already mentioned on facebook, I can't get the plugin to work in my local Joomla test sites. Each click on the like button results in the following error in my browser console: 
<img width="649" alt="J3_WT_Content_Like_JS_error_Screenshot 2022-04-12" src="https://user-images.githubusercontent.com/1189521/163027515-bdcaa8c7-a8fc-481b-a80c-e53f8131c650.png">

WT Content Like Plugin 1.0.2
Latest Joomla 3.10.x
Latest Joomla 4.1.x 

I have tested with all my current browsers. Safari, Chrome, FireFox. 
The error is always the same.

**Comment by sergeytolkachyov** [comment]
Hello. Can you let some details? What browser? Joomla version (3.2 or 3.10 is a big difference)?

**Comment by pepperstreet** [comment]
> Hello. Can you let some details? What browser? Joomla version (3.2 or 3.10 is a big difference)?

I have tested 2 other installations and different browsers. Please, see my initial updated post.

**Comment by sergeytolkachyov** [comment]
Try to open this url in browser with your own article id:
index.php?option=com_ajax&plugin=wt_content_like&group=content&format=raw&article_id=**23**

![123](https://user-images.githubusercontent.com/6236403/163912136-0f7f3221-6f21-4093-b9a2-c316abcf14b5.jpg)

**Comment by pepperstreet** [comment]
Calling the following URL with my article ID 5... 
_/joomla/index.php/en/?option=com_ajax&plugin=wt_content_like&group=content&format=raw&article_id=5_

Results in browser output:
**{"success":1,"message":"Thank you for rating this article.","rating":"1"}**

**Comment by sergeytolkachyov** [comment]
Try to add `Factory::getApplication()->setHeader('Content-Type', 'application/json');` before  `return $this->storeVote($data['article_id']);` in https://github.com/sergeytolkachyov/WT-Content-Like/blob/cce8e80a7b6cba1942708eb9d5cf9d490ed4a1a0/wt_content_like.php#L137 
I haven't an iOS gadgets to debug (

**Comment by pepperstreet** [comment]
Sorry, one year later... ;) Almost forgot about this personal local test. 
Just stumbled upon your JED entries and it reminded me on your "like" plugin. 

Your previous comment and suggestion seem to work! 
Like does work now and text message appears after second click. 

---

By the way, is there any chance or functionality to "dislike" an article... or let's say "revoke the like"?

**Comment by sergeytolkachyov** [comment]
> Кстати, есть ли возможность или функционал поставить "дизлайк" статье... или скажем "отменить лайк"?

This plugin is essentially a wrapper for the standard Joomla article rating. 1 like is 5 stars of the standard rating.  Joomla does not store links between likes and users. Stores only the IP of the last person who voted. In order to dislike, you can try to subtract a certain number from the current rating. But we risk facing a situation when the article has not yet had votes and it is given a minus. I don't know yet how Joomla will behave with negative numbers for rating in the database.
Or you need to write your own separate solution completely. But I haven't had such a task yet.
