### ISSUE TITLE
Не нажимается кнопка

### ISSUE THREAD

**Issue by 1inkin** [sergeytolkachyov/WT-Content-Like#3]
Приветствую. Установил Ваш плагин на сайт с Joomla 4.2.3. Кнопка палец вверх отображается, но при нажатии ничего не происходит и в консоли браузера ничего не отображает по этому поводу. Подскажите, чем может быть проблема?

**Comment by sergeytolkachyov** [comment]
Здравствуйте. js-файл загрузился из папки media?

**Comment by 1inkin** [comment]
![20221024_101110](https://user-images.githubusercontent.com/16318416/197468080-67c81c14-96ef-4ee6-8768-212f44cbbf22.jpg)
Похоже, что нет

**Comment by sergeytolkachyov** [comment]
В папке с медиа есть он?

**Comment by 1inkin** [comment]
Да, в /plugins/content/wt_content_like все файлы из установочного архива скопировались. В админпанели никаких проблем с плагином не неблюдается - открывается, включается. Стандартный плагин оценки отключен. Joomla 4.2.3 пустая, поэтому какието сторонние компоненты не влияют на работу.

**Comment by sergeytolkachyov** [comment]
Спасибо, нашёл случайную ошибку в xml-манифесте. Исправлено.

**Comment by 1inkin** [comment]
Спасибо, работает. Благодарю за отличный плагин

**Comment by sergeytolkachyov** [comment]
Не за что ) Спасибо.
