### ISSUE TITLE
Help, update plugin from Joomla 3 to Joomla 4.

### ISSUE THREAD

**Issue by emerson-pj** [sergeytolkachyov/WT-Content-Like#5]
Help, update plugin from Joomla 3 to Joomla 4.

Hello how are you ?

Could you help me to update the "contentmulticategories.php" file.

The plugin https://github.com/Arkadiy-Sedelnikov/ContentMulticategories
it works in Joomla 3, but in Joomla 4 the plugin is displayed in different place.

![image](https://github.com/sergeytolkachyov/WT-Content-Like/assets/71271000/f39791d2-dd50-4215-b35c-81dab8ff5129)

**Comment by sergeytolkachyov** [comment]
@emerson-pj hello. Does this plugin still works correctly on Joomla 4?

**Comment by emerson-pj** [comment]
@sergeytolkachyov Hello,
Yes, it works fine in Joomla 4.
Originally it was made for Joomla 3.
I modified the "category35.php" file to work in Joomla 4.
It works on Joomla 4, but the position is bad.

**Comment by sergeytolkachyov** [comment]
Now I'm busy with updating JL Content field filter. Remind me later, please. May be I'll can help you.
