### ISSUE TITLE
Не работает в пункте меню Избранные материалы

### ISSUE THREAD

**Issue by mediafoks** [sergeytolkachyov/WT-Content-Like#8]
Добрый вечер!
Joomla 5.0.0, чистая, только что установленная, поставил только плагин WT-Content-Like, больше ничего нет.
Ситуация такая, имеется пункт меню "Избранные материалы", соответственно выводит избранные материалы.
Content-Like не работает на данной странице, т.е. не выводится вообще.
Если открыть сам материал, то всё работает прекрасно, Content-Like выводится.
А дальше совсем чудеса.
Также на странице "Избранные материалы" имеется модуль Новостей. Так вот, Content-Like и в модуле не выводится.
НО, если сделать любой другой пункт меню, отличный от "Избранные материалы", например "Блог категории", то плагин начинает работать и в Блоге и в модуле Новостей тоже выводится.  Но как только пункт меню меняешь на "Избранные материалы", всё, на этой странице плагин ничего не выводит, ни в самих Избранных материалах, ни в модуле Новостей. 
Почините пожалуйста, уж очень хороший плагин, альтернативу не нашел.

**Comment by sergeytolkachyov** [comment]
Прочел. В скором времени постараюсь посмотреть. Так как тоже использую его на проектах.

**Comment by mediafoks** [comment]
Также не работает в com_tags. Например, пункт меню "Теги", на странице опубликован модуль, например "Новости". Соответственно будет $view === 'tag'. При таком раскладе в модуле "Новости" Content-Like не выводится.
Вобщем, при $view === 'featured' и $view === 'tag' Content-Like не работает.
Жаль.
